// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckUnReadMessageInfo.proto

package com.magicalign.OrthoLink.protobuf;

public final class ExaminationProtos {
  private ExaminationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ExaminationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Examination)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 examinationtypeid = 2;</code>
     */
    boolean hasExaminationtypeid();
    /**
     * <code>optional int32 examinationtypeid = 2;</code>
     */
    int getExaminationtypeid();

    /**
     * <code>optional int32 questiontypeid = 3;</code>
     */
    boolean hasQuestiontypeid();
    /**
     * <code>optional int32 questiontypeid = 3;</code>
     */
    int getQuestiontypeid();

    /**
     * <code>optional string question = 4;</code>
     */
    boolean hasQuestion();
    /**
     * <code>optional string question = 4;</code>
     */
    java.lang.String getQuestion();
    /**
     * <code>optional string question = 4;</code>
     */
    com.google.protobuf.ByteString
        getQuestionBytes();

    /**
     * <code>optional string answera = 5;</code>
     */
    boolean hasAnswera();
    /**
     * <code>optional string answera = 5;</code>
     */
    java.lang.String getAnswera();
    /**
     * <code>optional string answera = 5;</code>
     */
    com.google.protobuf.ByteString
        getAnsweraBytes();

    /**
     * <code>optional string answerb = 6;</code>
     */
    boolean hasAnswerb();
    /**
     * <code>optional string answerb = 6;</code>
     */
    java.lang.String getAnswerb();
    /**
     * <code>optional string answerb = 6;</code>
     */
    com.google.protobuf.ByteString
        getAnswerbBytes();

    /**
     * <code>optional string answerc = 7;</code>
     */
    boolean hasAnswerc();
    /**
     * <code>optional string answerc = 7;</code>
     */
    java.lang.String getAnswerc();
    /**
     * <code>optional string answerc = 7;</code>
     */
    com.google.protobuf.ByteString
        getAnswercBytes();

    /**
     * <code>optional string answerd = 8;</code>
     */
    boolean hasAnswerd();
    /**
     * <code>optional string answerd = 8;</code>
     */
    java.lang.String getAnswerd();
    /**
     * <code>optional string answerd = 8;</code>
     */
    com.google.protobuf.ByteString
        getAnswerdBytes();

    /**
     * <code>optional string answere = 9;</code>
     */
    boolean hasAnswere();
    /**
     * <code>optional string answere = 9;</code>
     */
    java.lang.String getAnswere();
    /**
     * <code>optional string answere = 9;</code>
     */
    com.google.protobuf.ByteString
        getAnswereBytes();

    /**
     * <code>optional string answerf = 10;</code>
     */
    boolean hasAnswerf();
    /**
     * <code>optional string answerf = 10;</code>
     */
    java.lang.String getAnswerf();
    /**
     * <code>optional string answerf = 10;</code>
     */
    com.google.protobuf.ByteString
        getAnswerfBytes();

    /**
     * <code>optional string answerg = 11;</code>
     */
    boolean hasAnswerg();
    /**
     * <code>optional string answerg = 11;</code>
     */
    java.lang.String getAnswerg();
    /**
     * <code>optional string answerg = 11;</code>
     */
    com.google.protobuf.ByteString
        getAnswergBytes();

    /**
     * <code>optional int32 trueanswer = 12;</code>
     */
    boolean hasTrueanswer();
    /**
     * <code>optional int32 trueanswer = 12;</code>
     */
    int getTrueanswer();

    /**
     * <code>optional string explain = 13;</code>
     */
    boolean hasExplain();
    /**
     * <code>optional string explain = 13;</code>
     */
    java.lang.String getExplain();
    /**
     * <code>optional string explain = 13;</code>
     */
    com.google.protobuf.ByteString
        getExplainBytes();

    /**
     * <code>optional int32 wrongnumber = 14;</code>
     */
    boolean hasWrongnumber();
    /**
     * <code>optional int32 wrongnumber = 14;</code>
     */
    int getWrongnumber();

    /**
     * <code>optional int32 totalnumber = 15;</code>
     */
    boolean hasTotalnumber();
    /**
     * <code>optional int32 totalnumber = 15;</code>
     */
    int getTotalnumber();
  }
  /**
   * Protobuf type {@code protobuf.Examination}
   */
  public static final class Examination extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.Examination)
      ExaminationOrBuilder {
    // Use Examination.newBuilder() to construct.
    private Examination(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Examination(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Examination defaultInstance;
    public static Examination getDefaultInstance() {
      return defaultInstance;
    }

    public Examination getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Examination(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              examinationtypeid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              questiontypeid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              question_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              answera_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              answerb_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              answerc_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              answerd_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              answere_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              answerf_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              answerg_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              trueanswer_ = input.readInt32();
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              explain_ = bs;
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              wrongnumber_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              totalnumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_Examination_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_Examination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.class, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder.class);
    }

    public static com.google.protobuf.Parser<Examination> PARSER =
        new com.google.protobuf.AbstractParser<Examination>() {
      public Examination parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Examination(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Examination> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EXAMINATIONTYPEID_FIELD_NUMBER = 2;
    private int examinationtypeid_;
    /**
     * <code>optional int32 examinationtypeid = 2;</code>
     */
    public boolean hasExaminationtypeid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 examinationtypeid = 2;</code>
     */
    public int getExaminationtypeid() {
      return examinationtypeid_;
    }

    public static final int QUESTIONTYPEID_FIELD_NUMBER = 3;
    private int questiontypeid_;
    /**
     * <code>optional int32 questiontypeid = 3;</code>
     */
    public boolean hasQuestiontypeid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 questiontypeid = 3;</code>
     */
    public int getQuestiontypeid() {
      return questiontypeid_;
    }

    public static final int QUESTION_FIELD_NUMBER = 4;
    private java.lang.Object question_;
    /**
     * <code>optional string question = 4;</code>
     */
    public boolean hasQuestion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string question = 4;</code>
     */
    public java.lang.String getQuestion() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          question_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string question = 4;</code>
     */
    public com.google.protobuf.ByteString
        getQuestionBytes() {
      java.lang.Object ref = question_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        question_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERA_FIELD_NUMBER = 5;
    private java.lang.Object answera_;
    /**
     * <code>optional string answera = 5;</code>
     */
    public boolean hasAnswera() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string answera = 5;</code>
     */
    public java.lang.String getAnswera() {
      java.lang.Object ref = answera_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answera_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answera = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAnsweraBytes() {
      java.lang.Object ref = answera_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answera_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERB_FIELD_NUMBER = 6;
    private java.lang.Object answerb_;
    /**
     * <code>optional string answerb = 6;</code>
     */
    public boolean hasAnswerb() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string answerb = 6;</code>
     */
    public java.lang.String getAnswerb() {
      java.lang.Object ref = answerb_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answerb_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answerb = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerbBytes() {
      java.lang.Object ref = answerb_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answerb_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERC_FIELD_NUMBER = 7;
    private java.lang.Object answerc_;
    /**
     * <code>optional string answerc = 7;</code>
     */
    public boolean hasAnswerc() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string answerc = 7;</code>
     */
    public java.lang.String getAnswerc() {
      java.lang.Object ref = answerc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answerc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answerc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAnswercBytes() {
      java.lang.Object ref = answerc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answerc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERD_FIELD_NUMBER = 8;
    private java.lang.Object answerd_;
    /**
     * <code>optional string answerd = 8;</code>
     */
    public boolean hasAnswerd() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string answerd = 8;</code>
     */
    public java.lang.String getAnswerd() {
      java.lang.Object ref = answerd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answerd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answerd = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerdBytes() {
      java.lang.Object ref = answerd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answerd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERE_FIELD_NUMBER = 9;
    private java.lang.Object answere_;
    /**
     * <code>optional string answere = 9;</code>
     */
    public boolean hasAnswere() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string answere = 9;</code>
     */
    public java.lang.String getAnswere() {
      java.lang.Object ref = answere_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answere_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answere = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAnswereBytes() {
      java.lang.Object ref = answere_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answere_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERF_FIELD_NUMBER = 10;
    private java.lang.Object answerf_;
    /**
     * <code>optional string answerf = 10;</code>
     */
    public boolean hasAnswerf() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string answerf = 10;</code>
     */
    public java.lang.String getAnswerf() {
      java.lang.Object ref = answerf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answerf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answerf = 10;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerfBytes() {
      java.lang.Object ref = answerf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answerf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANSWERG_FIELD_NUMBER = 11;
    private java.lang.Object answerg_;
    /**
     * <code>optional string answerg = 11;</code>
     */
    public boolean hasAnswerg() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string answerg = 11;</code>
     */
    public java.lang.String getAnswerg() {
      java.lang.Object ref = answerg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answerg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answerg = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAnswergBytes() {
      java.lang.Object ref = answerg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answerg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRUEANSWER_FIELD_NUMBER = 12;
    private int trueanswer_;
    /**
     * <code>optional int32 trueanswer = 12;</code>
     */
    public boolean hasTrueanswer() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 trueanswer = 12;</code>
     */
    public int getTrueanswer() {
      return trueanswer_;
    }

    public static final int EXPLAIN_FIELD_NUMBER = 13;
    private java.lang.Object explain_;
    /**
     * <code>optional string explain = 13;</code>
     */
    public boolean hasExplain() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string explain = 13;</code>
     */
    public java.lang.String getExplain() {
      java.lang.Object ref = explain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          explain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string explain = 13;</code>
     */
    public com.google.protobuf.ByteString
        getExplainBytes() {
      java.lang.Object ref = explain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        explain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WRONGNUMBER_FIELD_NUMBER = 14;
    private int wrongnumber_;
    /**
     * <code>optional int32 wrongnumber = 14;</code>
     */
    public boolean hasWrongnumber() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 wrongnumber = 14;</code>
     */
    public int getWrongnumber() {
      return wrongnumber_;
    }

    public static final int TOTALNUMBER_FIELD_NUMBER = 15;
    private int totalnumber_;
    /**
     * <code>optional int32 totalnumber = 15;</code>
     */
    public boolean hasTotalnumber() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional int32 totalnumber = 15;</code>
     */
    public int getTotalnumber() {
      return totalnumber_;
    }

    private void initFields() {
      id_ = 0;
      examinationtypeid_ = 0;
      questiontypeid_ = 0;
      question_ = "";
      answera_ = "";
      answerb_ = "";
      answerc_ = "";
      answerd_ = "";
      answere_ = "";
      answerf_ = "";
      answerg_ = "";
      trueanswer_ = 0;
      explain_ = "";
      wrongnumber_ = 0;
      totalnumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, examinationtypeid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, questiontypeid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getQuestionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAnsweraBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getAnswerbBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getAnswercBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getAnswerdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getAnswereBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getAnswerfBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getAnswergBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, trueanswer_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getExplainBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, wrongnumber_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeInt32(15, totalnumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, examinationtypeid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, questiontypeid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getQuestionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAnsweraBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAnswerbBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getAnswercBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getAnswerdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getAnswereBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getAnswerfBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getAnswergBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, trueanswer_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getExplainBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, wrongnumber_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, totalnumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Examination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Examination)
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_Examination_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_Examination_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.class, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder.class);
      }

      // Construct using com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        examinationtypeid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        questiontypeid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        question_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        answera_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        answerb_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        answerc_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        answerd_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        answere_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        answerf_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        answerg_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        trueanswer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        explain_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        wrongnumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        totalnumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_Examination_descriptor;
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination getDefaultInstanceForType() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.getDefaultInstance();
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination build() {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination buildPartial() {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination result = new com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.examinationtypeid_ = examinationtypeid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.questiontypeid_ = questiontypeid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.question_ = question_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.answera_ = answera_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.answerb_ = answerb_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.answerc_ = answerc_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.answerd_ = answerd_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.answere_ = answere_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.answerf_ = answerf_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.answerg_ = answerg_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.trueanswer_ = trueanswer_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.explain_ = explain_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.wrongnumber_ = wrongnumber_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.totalnumber_ = totalnumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination) {
          return mergeFrom((com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination other) {
        if (other == com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasExaminationtypeid()) {
          setExaminationtypeid(other.getExaminationtypeid());
        }
        if (other.hasQuestiontypeid()) {
          setQuestiontypeid(other.getQuestiontypeid());
        }
        if (other.hasQuestion()) {
          bitField0_ |= 0x00000008;
          question_ = other.question_;
          onChanged();
        }
        if (other.hasAnswera()) {
          bitField0_ |= 0x00000010;
          answera_ = other.answera_;
          onChanged();
        }
        if (other.hasAnswerb()) {
          bitField0_ |= 0x00000020;
          answerb_ = other.answerb_;
          onChanged();
        }
        if (other.hasAnswerc()) {
          bitField0_ |= 0x00000040;
          answerc_ = other.answerc_;
          onChanged();
        }
        if (other.hasAnswerd()) {
          bitField0_ |= 0x00000080;
          answerd_ = other.answerd_;
          onChanged();
        }
        if (other.hasAnswere()) {
          bitField0_ |= 0x00000100;
          answere_ = other.answere_;
          onChanged();
        }
        if (other.hasAnswerf()) {
          bitField0_ |= 0x00000200;
          answerf_ = other.answerf_;
          onChanged();
        }
        if (other.hasAnswerg()) {
          bitField0_ |= 0x00000400;
          answerg_ = other.answerg_;
          onChanged();
        }
        if (other.hasTrueanswer()) {
          setTrueanswer(other.getTrueanswer());
        }
        if (other.hasExplain()) {
          bitField0_ |= 0x00001000;
          explain_ = other.explain_;
          onChanged();
        }
        if (other.hasWrongnumber()) {
          setWrongnumber(other.getWrongnumber());
        }
        if (other.hasTotalnumber()) {
          setTotalnumber(other.getTotalnumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int examinationtypeid_ ;
      /**
       * <code>optional int32 examinationtypeid = 2;</code>
       */
      public boolean hasExaminationtypeid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 examinationtypeid = 2;</code>
       */
      public int getExaminationtypeid() {
        return examinationtypeid_;
      }
      /**
       * <code>optional int32 examinationtypeid = 2;</code>
       */
      public Builder setExaminationtypeid(int value) {
        bitField0_ |= 0x00000002;
        examinationtypeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 examinationtypeid = 2;</code>
       */
      public Builder clearExaminationtypeid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        examinationtypeid_ = 0;
        onChanged();
        return this;
      }

      private int questiontypeid_ ;
      /**
       * <code>optional int32 questiontypeid = 3;</code>
       */
      public boolean hasQuestiontypeid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 questiontypeid = 3;</code>
       */
      public int getQuestiontypeid() {
        return questiontypeid_;
      }
      /**
       * <code>optional int32 questiontypeid = 3;</code>
       */
      public Builder setQuestiontypeid(int value) {
        bitField0_ |= 0x00000004;
        questiontypeid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 questiontypeid = 3;</code>
       */
      public Builder clearQuestiontypeid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        questiontypeid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object question_ = "";
      /**
       * <code>optional string question = 4;</code>
       */
      public boolean hasQuestion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string question = 4;</code>
       */
      public java.lang.String getQuestion() {
        java.lang.Object ref = question_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            question_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string question = 4;</code>
       */
      public com.google.protobuf.ByteString
          getQuestionBytes() {
        java.lang.Object ref = question_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          question_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string question = 4;</code>
       */
      public Builder setQuestion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        question_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string question = 4;</code>
       */
      public Builder clearQuestion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        question_ = getDefaultInstance().getQuestion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string question = 4;</code>
       */
      public Builder setQuestionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        question_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answera_ = "";
      /**
       * <code>optional string answera = 5;</code>
       */
      public boolean hasAnswera() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string answera = 5;</code>
       */
      public java.lang.String getAnswera() {
        java.lang.Object ref = answera_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answera_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answera = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAnsweraBytes() {
        java.lang.Object ref = answera_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answera_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answera = 5;</code>
       */
      public Builder setAnswera(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        answera_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answera = 5;</code>
       */
      public Builder clearAnswera() {
        bitField0_ = (bitField0_ & ~0x00000010);
        answera_ = getDefaultInstance().getAnswera();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answera = 5;</code>
       */
      public Builder setAnsweraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        answera_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answerb_ = "";
      /**
       * <code>optional string answerb = 6;</code>
       */
      public boolean hasAnswerb() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string answerb = 6;</code>
       */
      public java.lang.String getAnswerb() {
        java.lang.Object ref = answerb_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answerb_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answerb = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerbBytes() {
        java.lang.Object ref = answerb_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answerb_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answerb = 6;</code>
       */
      public Builder setAnswerb(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        answerb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerb = 6;</code>
       */
      public Builder clearAnswerb() {
        bitField0_ = (bitField0_ & ~0x00000020);
        answerb_ = getDefaultInstance().getAnswerb();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerb = 6;</code>
       */
      public Builder setAnswerbBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        answerb_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answerc_ = "";
      /**
       * <code>optional string answerc = 7;</code>
       */
      public boolean hasAnswerc() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string answerc = 7;</code>
       */
      public java.lang.String getAnswerc() {
        java.lang.Object ref = answerc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answerc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answerc = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAnswercBytes() {
        java.lang.Object ref = answerc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answerc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answerc = 7;</code>
       */
      public Builder setAnswerc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        answerc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerc = 7;</code>
       */
      public Builder clearAnswerc() {
        bitField0_ = (bitField0_ & ~0x00000040);
        answerc_ = getDefaultInstance().getAnswerc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerc = 7;</code>
       */
      public Builder setAnswercBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        answerc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answerd_ = "";
      /**
       * <code>optional string answerd = 8;</code>
       */
      public boolean hasAnswerd() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string answerd = 8;</code>
       */
      public java.lang.String getAnswerd() {
        java.lang.Object ref = answerd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answerd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answerd = 8;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerdBytes() {
        java.lang.Object ref = answerd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answerd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answerd = 8;</code>
       */
      public Builder setAnswerd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        answerd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerd = 8;</code>
       */
      public Builder clearAnswerd() {
        bitField0_ = (bitField0_ & ~0x00000080);
        answerd_ = getDefaultInstance().getAnswerd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerd = 8;</code>
       */
      public Builder setAnswerdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        answerd_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answere_ = "";
      /**
       * <code>optional string answere = 9;</code>
       */
      public boolean hasAnswere() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string answere = 9;</code>
       */
      public java.lang.String getAnswere() {
        java.lang.Object ref = answere_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answere_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answere = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAnswereBytes() {
        java.lang.Object ref = answere_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answere_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answere = 9;</code>
       */
      public Builder setAnswere(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        answere_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answere = 9;</code>
       */
      public Builder clearAnswere() {
        bitField0_ = (bitField0_ & ~0x00000100);
        answere_ = getDefaultInstance().getAnswere();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answere = 9;</code>
       */
      public Builder setAnswereBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        answere_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answerf_ = "";
      /**
       * <code>optional string answerf = 10;</code>
       */
      public boolean hasAnswerf() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string answerf = 10;</code>
       */
      public java.lang.String getAnswerf() {
        java.lang.Object ref = answerf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answerf_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answerf = 10;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerfBytes() {
        java.lang.Object ref = answerf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answerf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answerf = 10;</code>
       */
      public Builder setAnswerf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        answerf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerf = 10;</code>
       */
      public Builder clearAnswerf() {
        bitField0_ = (bitField0_ & ~0x00000200);
        answerf_ = getDefaultInstance().getAnswerf();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerf = 10;</code>
       */
      public Builder setAnswerfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        answerf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object answerg_ = "";
      /**
       * <code>optional string answerg = 11;</code>
       */
      public boolean hasAnswerg() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string answerg = 11;</code>
       */
      public java.lang.String getAnswerg() {
        java.lang.Object ref = answerg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answerg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answerg = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAnswergBytes() {
        java.lang.Object ref = answerg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answerg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answerg = 11;</code>
       */
      public Builder setAnswerg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        answerg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerg = 11;</code>
       */
      public Builder clearAnswerg() {
        bitField0_ = (bitField0_ & ~0x00000400);
        answerg_ = getDefaultInstance().getAnswerg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answerg = 11;</code>
       */
      public Builder setAnswergBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        answerg_ = value;
        onChanged();
        return this;
      }

      private int trueanswer_ ;
      /**
       * <code>optional int32 trueanswer = 12;</code>
       */
      public boolean hasTrueanswer() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 trueanswer = 12;</code>
       */
      public int getTrueanswer() {
        return trueanswer_;
      }
      /**
       * <code>optional int32 trueanswer = 12;</code>
       */
      public Builder setTrueanswer(int value) {
        bitField0_ |= 0x00000800;
        trueanswer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 trueanswer = 12;</code>
       */
      public Builder clearTrueanswer() {
        bitField0_ = (bitField0_ & ~0x00000800);
        trueanswer_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object explain_ = "";
      /**
       * <code>optional string explain = 13;</code>
       */
      public boolean hasExplain() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string explain = 13;</code>
       */
      public java.lang.String getExplain() {
        java.lang.Object ref = explain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            explain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string explain = 13;</code>
       */
      public com.google.protobuf.ByteString
          getExplainBytes() {
        java.lang.Object ref = explain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          explain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string explain = 13;</code>
       */
      public Builder setExplain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        explain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string explain = 13;</code>
       */
      public Builder clearExplain() {
        bitField0_ = (bitField0_ & ~0x00001000);
        explain_ = getDefaultInstance().getExplain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string explain = 13;</code>
       */
      public Builder setExplainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        explain_ = value;
        onChanged();
        return this;
      }

      private int wrongnumber_ ;
      /**
       * <code>optional int32 wrongnumber = 14;</code>
       */
      public boolean hasWrongnumber() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 wrongnumber = 14;</code>
       */
      public int getWrongnumber() {
        return wrongnumber_;
      }
      /**
       * <code>optional int32 wrongnumber = 14;</code>
       */
      public Builder setWrongnumber(int value) {
        bitField0_ |= 0x00002000;
        wrongnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 wrongnumber = 14;</code>
       */
      public Builder clearWrongnumber() {
        bitField0_ = (bitField0_ & ~0x00002000);
        wrongnumber_ = 0;
        onChanged();
        return this;
      }

      private int totalnumber_ ;
      /**
       * <code>optional int32 totalnumber = 15;</code>
       */
      public boolean hasTotalnumber() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 totalnumber = 15;</code>
       */
      public int getTotalnumber() {
        return totalnumber_;
      }
      /**
       * <code>optional int32 totalnumber = 15;</code>
       */
      public Builder setTotalnumber(int value) {
        bitField0_ |= 0x00004000;
        totalnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 totalnumber = 15;</code>
       */
      public Builder clearTotalnumber() {
        bitField0_ = (bitField0_ & ~0x00004000);
        totalnumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Examination)
    }

    static {
      defaultInstance = new Examination(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Examination)
  }

  public interface ExaminationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.ExaminationList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> 
        getExaminationList();
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination getExamination(int index);
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    int getExaminationCount();
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    java.util.List<? extends com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder> 
        getExaminationOrBuilderList();
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder getExaminationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.ExaminationList}
   */
  public static final class ExaminationList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.ExaminationList)
      ExaminationListOrBuilder {
    // Use ExaminationList.newBuilder() to construct.
    private ExaminationList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExaminationList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExaminationList defaultInstance;
    public static ExaminationList getDefaultInstance() {
      return defaultInstance;
    }

    public ExaminationList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExaminationList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                examination_ = new java.util.ArrayList<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination>();
                mutable_bitField0_ |= 0x00000001;
              }
              examination_.add(input.readMessage(com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          examination_ = java.util.Collections.unmodifiableList(examination_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_ExaminationList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_ExaminationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.class, com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.Builder.class);
    }

    public static com.google.protobuf.Parser<ExaminationList> PARSER =
        new com.google.protobuf.AbstractParser<ExaminationList>() {
      public ExaminationList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExaminationList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExaminationList> getParserForType() {
      return PARSER;
    }

    public static final int EXAMINATION_FIELD_NUMBER = 1;
    private java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> examination_;
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    public java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> getExaminationList() {
      return examination_;
    }
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    public java.util.List<? extends com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder> 
        getExaminationOrBuilderList() {
      return examination_;
    }
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    public int getExaminationCount() {
      return examination_.size();
    }
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination getExamination(int index) {
      return examination_.get(index);
    }
    /**
     * <code>repeated .protobuf.Examination Examination = 1;</code>
     */
    public com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder getExaminationOrBuilder(
        int index) {
      return examination_.get(index);
    }

    private void initFields() {
      examination_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < examination_.size(); i++) {
        output.writeMessage(1, examination_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < examination_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, examination_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.ExaminationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.ExaminationList)
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_ExaminationList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_ExaminationList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.class, com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.Builder.class);
      }

      // Construct using com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getExaminationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (examinationBuilder_ == null) {
          examination_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          examinationBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.internal_static_protobuf_ExaminationList_descriptor;
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList getDefaultInstanceForType() {
        return com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.getDefaultInstance();
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList build() {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList buildPartial() {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList result = new com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList(this);
        int from_bitField0_ = bitField0_;
        if (examinationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            examination_ = java.util.Collections.unmodifiableList(examination_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.examination_ = examination_;
        } else {
          result.examination_ = examinationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList) {
          return mergeFrom((com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList other) {
        if (other == com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList.getDefaultInstance()) return this;
        if (examinationBuilder_ == null) {
          if (!other.examination_.isEmpty()) {
            if (examination_.isEmpty()) {
              examination_ = other.examination_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureExaminationIsMutable();
              examination_.addAll(other.examination_);
            }
            onChanged();
          }
        } else {
          if (!other.examination_.isEmpty()) {
            if (examinationBuilder_.isEmpty()) {
              examinationBuilder_.dispose();
              examinationBuilder_ = null;
              examination_ = other.examination_;
              bitField0_ = (bitField0_ & ~0x00000001);
              examinationBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getExaminationFieldBuilder() : null;
            } else {
              examinationBuilder_.addAllMessages(other.examination_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> examination_ =
        java.util.Collections.emptyList();
      private void ensureExaminationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          examination_ = new java.util.ArrayList<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination>(examination_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder, com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder> examinationBuilder_;

      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> getExaminationList() {
        if (examinationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(examination_);
        } else {
          return examinationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public int getExaminationCount() {
        if (examinationBuilder_ == null) {
          return examination_.size();
        } else {
          return examinationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination getExamination(int index) {
        if (examinationBuilder_ == null) {
          return examination_.get(index);
        } else {
          return examinationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder setExamination(
          int index, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination value) {
        if (examinationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExaminationIsMutable();
          examination_.set(index, value);
          onChanged();
        } else {
          examinationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder setExamination(
          int index, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder builderForValue) {
        if (examinationBuilder_ == null) {
          ensureExaminationIsMutable();
          examination_.set(index, builderForValue.build());
          onChanged();
        } else {
          examinationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder addExamination(com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination value) {
        if (examinationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExaminationIsMutable();
          examination_.add(value);
          onChanged();
        } else {
          examinationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder addExamination(
          int index, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination value) {
        if (examinationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExaminationIsMutable();
          examination_.add(index, value);
          onChanged();
        } else {
          examinationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder addExamination(
          com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder builderForValue) {
        if (examinationBuilder_ == null) {
          ensureExaminationIsMutable();
          examination_.add(builderForValue.build());
          onChanged();
        } else {
          examinationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder addExamination(
          int index, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder builderForValue) {
        if (examinationBuilder_ == null) {
          ensureExaminationIsMutable();
          examination_.add(index, builderForValue.build());
          onChanged();
        } else {
          examinationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder addAllExamination(
          java.lang.Iterable<? extends com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination> values) {
        if (examinationBuilder_ == null) {
          ensureExaminationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, examination_);
          onChanged();
        } else {
          examinationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder clearExamination() {
        if (examinationBuilder_ == null) {
          examination_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          examinationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public Builder removeExamination(int index) {
        if (examinationBuilder_ == null) {
          ensureExaminationIsMutable();
          examination_.remove(index);
          onChanged();
        } else {
          examinationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder getExaminationBuilder(
          int index) {
        return getExaminationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder getExaminationOrBuilder(
          int index) {
        if (examinationBuilder_ == null) {
          return examination_.get(index);  } else {
          return examinationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public java.util.List<? extends com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder> 
           getExaminationOrBuilderList() {
        if (examinationBuilder_ != null) {
          return examinationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(examination_);
        }
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder addExaminationBuilder() {
        return getExaminationFieldBuilder().addBuilder(
            com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder addExaminationBuilder(
          int index) {
        return getExaminationFieldBuilder().addBuilder(
            index, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Examination Examination = 1;</code>
       */
      public java.util.List<com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder> 
           getExaminationBuilderList() {
        return getExaminationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder, com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder> 
          getExaminationFieldBuilder() {
        if (examinationBuilder_ == null) {
          examinationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination, com.magicalign.OrthoLink.protobuf.ExaminationProtos.Examination.Builder, com.magicalign.OrthoLink.protobuf.ExaminationProtos.ExaminationOrBuilder>(
                  examination_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          examination_ = null;
        }
        return examinationBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.ExaminationList)
    }

    static {
      defaultInstance = new ExaminationList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.ExaminationList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Examination_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Examination_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_ExaminationList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_ExaminationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CheckUnReadMessageInfo.proto\022\010protobuf" +
      "\"\244\002\n\013Examination\022\n\n\002id\030\001 \001(\005\022\031\n\021examinat" +
      "iontypeid\030\002 \001(\005\022\026\n\016questiontypeid\030\003 \001(\005\022" +
      "\020\n\010question\030\004 \001(\t\022\017\n\007answera\030\005 \001(\t\022\017\n\007an" +
      "swerb\030\006 \001(\t\022\017\n\007answerc\030\007 \001(\t\022\017\n\007answerd\030" +
      "\010 \001(\t\022\017\n\007answere\030\t \001(\t\022\017\n\007answerf\030\n \001(\t\022" +
      "\017\n\007answerg\030\013 \001(\t\022\022\n\ntrueanswer\030\014 \001(\005\022\017\n\007" +
      "explain\030\r \001(\t\022\023\n\013wrongnumber\030\016 \001(\005\022\023\n\013to" +
      "talnumber\030\017 \001(\005\"=\n\017ExaminationList\022*\n\013Ex" +
      "amination\030\001 \003(\0132\025.protobuf.ExaminationB6",
      "\n!com.magicalign.OrthoLink.protobufB\021Exa" +
      "minationProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Examination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Examination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_Examination_descriptor,
        new java.lang.String[] { "Id", "Examinationtypeid", "Questiontypeid", "Question", "Answera", "Answerb", "Answerc", "Answerd", "Answere", "Answerf", "Answerg", "Trueanswer", "Explain", "Wrongnumber", "Totalnumber", });
    internal_static_protobuf_ExaminationList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_ExaminationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_ExaminationList_descriptor,
        new java.lang.String[] { "Examination", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
