// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CheckUnReadMessageInfo.proto

package com.magicalign.OrthoLink.protobuf;

public final class GetExaminationProtos {
  private GetExaminationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetExaminationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.GetExamination)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 ExaminationTypeId = 1;</code>
     */
    boolean hasExaminationTypeId();
    /**
     * <code>optional int32 ExaminationTypeId = 1;</code>
     */
    int getExaminationTypeId();

    /**
     * <code>optional int32 ExaminationForm = 2;</code>
     */
    boolean hasExaminationForm();
    /**
     * <code>optional int32 ExaminationForm = 2;</code>
     */
    int getExaminationForm();
  }
  /**
   * Protobuf type {@code protobuf.GetExamination}
   */
  public static final class GetExamination extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.GetExamination)
      GetExaminationOrBuilder {
    // Use GetExamination.newBuilder() to construct.
    private GetExamination(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetExamination(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetExamination defaultInstance;
    public static GetExamination getDefaultInstance() {
      return defaultInstance;
    }

    public GetExamination getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetExamination(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              examinationTypeId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              examinationForm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.internal_static_protobuf_GetExamination_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.internal_static_protobuf_GetExamination_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.class, com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.Builder.class);
    }

    public static com.google.protobuf.Parser<GetExamination> PARSER =
        new com.google.protobuf.AbstractParser<GetExamination>() {
      public GetExamination parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetExamination(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetExamination> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EXAMINATIONTYPEID_FIELD_NUMBER = 1;
    private int examinationTypeId_;
    /**
     * <code>optional int32 ExaminationTypeId = 1;</code>
     */
    public boolean hasExaminationTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 ExaminationTypeId = 1;</code>
     */
    public int getExaminationTypeId() {
      return examinationTypeId_;
    }

    public static final int EXAMINATIONFORM_FIELD_NUMBER = 2;
    private int examinationForm_;
    /**
     * <code>optional int32 ExaminationForm = 2;</code>
     */
    public boolean hasExaminationForm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 ExaminationForm = 2;</code>
     */
    public int getExaminationForm() {
      return examinationForm_;
    }

    private void initFields() {
      examinationTypeId_ = 0;
      examinationForm_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, examinationTypeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, examinationForm_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, examinationTypeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, examinationForm_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.GetExamination}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.GetExamination)
        com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExaminationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.internal_static_protobuf_GetExamination_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.internal_static_protobuf_GetExamination_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.class, com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.Builder.class);
      }

      // Construct using com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        examinationTypeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        examinationForm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.internal_static_protobuf_GetExamination_descriptor;
      }

      public com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination getDefaultInstanceForType() {
        return com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.getDefaultInstance();
      }

      public com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination build() {
        com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination buildPartial() {
        com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination result = new com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.examinationTypeId_ = examinationTypeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.examinationForm_ = examinationForm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination) {
          return mergeFrom((com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination other) {
        if (other == com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination.getDefaultInstance()) return this;
        if (other.hasExaminationTypeId()) {
          setExaminationTypeId(other.getExaminationTypeId());
        }
        if (other.hasExaminationForm()) {
          setExaminationForm(other.getExaminationForm());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.magicalign.OrthoLink.protobuf.GetExaminationProtos.GetExamination) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int examinationTypeId_ ;
      /**
       * <code>optional int32 ExaminationTypeId = 1;</code>
       */
      public boolean hasExaminationTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 ExaminationTypeId = 1;</code>
       */
      public int getExaminationTypeId() {
        return examinationTypeId_;
      }
      /**
       * <code>optional int32 ExaminationTypeId = 1;</code>
       */
      public Builder setExaminationTypeId(int value) {
        bitField0_ |= 0x00000001;
        examinationTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ExaminationTypeId = 1;</code>
       */
      public Builder clearExaminationTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        examinationTypeId_ = 0;
        onChanged();
        return this;
      }

      private int examinationForm_ ;
      /**
       * <code>optional int32 ExaminationForm = 2;</code>
       */
      public boolean hasExaminationForm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 ExaminationForm = 2;</code>
       */
      public int getExaminationForm() {
        return examinationForm_;
      }
      /**
       * <code>optional int32 ExaminationForm = 2;</code>
       */
      public Builder setExaminationForm(int value) {
        bitField0_ |= 0x00000002;
        examinationForm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ExaminationForm = 2;</code>
       */
      public Builder clearExaminationForm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        examinationForm_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.GetExamination)
    }

    static {
      defaultInstance = new GetExamination(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.GetExamination)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_GetExamination_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_GetExamination_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CheckUnReadMessageInfo.proto\022\010protobuf" +
      "\"D\n\016GetExamination\022\031\n\021ExaminationTypeId\030" +
      "\001 \001(\005\022\027\n\017ExaminationForm\030\002 \001(\005B9\n!com.ma" +
      "gicalign.OrthoLink.protobufB\024GetExaminat" +
      "ionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_GetExamination_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_GetExamination_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_GetExamination_descriptor,
        new java.lang.String[] { "ExaminationTypeId", "ExaminationForm", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
